/**
 * Mule NetSuite Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */

package org.mule.module.netsuite;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.mule.api.lifecycle.InitialisationException;
import org.mule.module.netsuite.api.model.entity.EntityType;

import java.util.Calendar;

import org.hamcrest.CoreMatchers;
import org.junit.Before;
import org.junit.Test;

public class NetSuiteTestDriver
{
    private NetSuiteCloudConnector connector;

    @Before
    public void setup() throws InitialisationException
    {
        connector = new NetSuiteCloudConnector();
        connector.initialise();
    }

    @Test
    public void getServerTime() throws Exception
    {
        assertThat(connector.getServerTime(), instanceOf(Calendar.class));
    }

    @Test
    public void getEntities() throws Exception
    {
        assertFalse(connector.getEntities(EntityType.ACCOUNT).isEmpty());
    }

}
