/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.netsuite;

import org.junit.Test;

import org.mule.module.netsuite.NetSuiteCloudConnector;

public class NetSuiteTestCase
{
    @Test
    public void invokeSomeMethodOnTheCloudConnector()
    {
    /*
        Add code that tests the cloud connector at the API level. This means that you'll
        instantiate your cloud connector directly, invoke one of its methods and assert
        you get the correct result.

        Example:

        NetSuiteCloudConnector connector = new NetSuiteCloudConnector();
        Object result = connector.someMethod("sample input");
        assertEquals("expected output", result);
     */
    }
}
