/**
 * Mule NetSuite Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */


package com.netsuite.webservices.platform_2010_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "asyncFault", targetNamespace = "urn:faults_2010_2.platform.webservices.netsuite.com")
public class AsyncFault extends Exception {
    public static final long serialVersionUID = 20110426173533L;
    
    private com.netsuite.webservices.platform.faults_2010_2.AsyncFault asyncFault;

    public AsyncFault() {
        super();
    }
    
    public AsyncFault(String message) {
        super(message);
    }
    
    public AsyncFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AsyncFault(String message, com.netsuite.webservices.platform.faults_2010_2.AsyncFault asyncFault) {
        super(message);
        this.asyncFault = asyncFault;
    }

    public AsyncFault(String message, com.netsuite.webservices.platform.faults_2010_2.AsyncFault asyncFault, Throwable cause) {
        super(message, cause);
        this.asyncFault = asyncFault;
    }

    public com.netsuite.webservices.platform.faults_2010_2.AsyncFault getFaultInfo() {
        return this.asyncFault;
    }
}
