
package com.netsuite.webservices.platform_2010_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "exceededRequestLimitFault", targetNamespace = "urn:faults_2010_2.platform.webservices.netsuite.com")
public class ExceededRequestLimitFault extends Exception {
    public static final long serialVersionUID = 20110426173533L;
    
    private com.netsuite.webservices.platform.faults_2010_2.ExceededRequestLimitFault exceededRequestLimitFault;

    public ExceededRequestLimitFault() {
        super();
    }
    
    public ExceededRequestLimitFault(String message) {
        super(message);
    }
    
    public ExceededRequestLimitFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRequestLimitFault(String message, com.netsuite.webservices.platform.faults_2010_2.ExceededRequestLimitFault exceededRequestLimitFault) {
        super(message);
        this.exceededRequestLimitFault = exceededRequestLimitFault;
    }

    public ExceededRequestLimitFault(String message, com.netsuite.webservices.platform.faults_2010_2.ExceededRequestLimitFault exceededRequestLimitFault, Throwable cause) {
        super(message, cause);
        this.exceededRequestLimitFault = exceededRequestLimitFault;
    }

    public com.netsuite.webservices.platform.faults_2010_2.ExceededRequestLimitFault getFaultInfo() {
        return this.exceededRequestLimitFault;
    }
}
