
package com.netsuite.webservices.platform_2010_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "exceededRecordCountFault", targetNamespace = "urn:faults_2010_2.platform.webservices.netsuite.com")
public class ExceededRecordCountFault extends Exception {
    public static final long serialVersionUID = 20110426173533L;
    
    private com.netsuite.webservices.platform.faults_2010_2.ExceededRecordCountFault exceededRecordCountFault;

    public ExceededRecordCountFault() {
        super();
    }
    
    public ExceededRecordCountFault(String message) {
        super(message);
    }
    
    public ExceededRecordCountFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRecordCountFault(String message, com.netsuite.webservices.platform.faults_2010_2.ExceededRecordCountFault exceededRecordCountFault) {
        super(message);
        this.exceededRecordCountFault = exceededRecordCountFault;
    }

    public ExceededRecordCountFault(String message, com.netsuite.webservices.platform.faults_2010_2.ExceededRecordCountFault exceededRecordCountFault, Throwable cause) {
        super(message, cause);
        this.exceededRecordCountFault = exceededRecordCountFault;
    }

    public com.netsuite.webservices.platform.faults_2010_2.ExceededRecordCountFault getFaultInfo() {
        return this.exceededRecordCountFault;
    }
}
