
package com.netsuite.webservices.platform_2010_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "invalidVersionFault", targetNamespace = "urn:faults_2010_2.platform.webservices.netsuite.com")
public class InvalidVersionFault extends Exception {
    public static final long serialVersionUID = 20110426173533L;
    
    private com.netsuite.webservices.platform.faults_2010_2.InvalidVersionFault invalidVersionFault;

    public InvalidVersionFault() {
        super();
    }
    
    public InvalidVersionFault(String message) {
        super(message);
    }
    
    public InvalidVersionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidVersionFault(String message, com.netsuite.webservices.platform.faults_2010_2.InvalidVersionFault invalidVersionFault) {
        super(message);
        this.invalidVersionFault = invalidVersionFault;
    }

    public InvalidVersionFault(String message, com.netsuite.webservices.platform.faults_2010_2.InvalidVersionFault invalidVersionFault, Throwable cause) {
        super(message, cause);
        this.invalidVersionFault = invalidVersionFault;
    }

    public com.netsuite.webservices.platform.faults_2010_2.InvalidVersionFault getFaultInfo() {
        return this.invalidVersionFault;
    }
}
