
package com.netsuite.webservices.platform_2010_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "invalidCredentialsFault", targetNamespace = "urn:faults_2010_2.platform.webservices.netsuite.com")
public class InvalidCredentialsFault extends Exception {
    public static final long serialVersionUID = 20110426173533L;
    
    private com.netsuite.webservices.platform.faults_2010_2.InvalidCredentialsFault invalidCredentialsFault;

    public InvalidCredentialsFault() {
        super();
    }
    
    public InvalidCredentialsFault(String message) {
        super(message);
    }
    
    public InvalidCredentialsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCredentialsFault(String message, com.netsuite.webservices.platform.faults_2010_2.InvalidCredentialsFault invalidCredentialsFault) {
        super(message);
        this.invalidCredentialsFault = invalidCredentialsFault;
    }

    public InvalidCredentialsFault(String message, com.netsuite.webservices.platform.faults_2010_2.InvalidCredentialsFault invalidCredentialsFault, Throwable cause) {
        super(message, cause);
        this.invalidCredentialsFault = invalidCredentialsFault;
    }

    public com.netsuite.webservices.platform.faults_2010_2.InvalidCredentialsFault getFaultInfo() {
        return this.invalidCredentialsFault;
    }
}
