
package com.netsuite.webservices.platform_2010_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "invalidSessionFault", targetNamespace = "urn:faults_2010_2.platform.webservices.netsuite.com")
public class InvalidSessionFault extends Exception {
    public static final long serialVersionUID = 20110426173533L;
    
    private com.netsuite.webservices.platform.faults_2010_2.InvalidSessionFault invalidSessionFault;

    public InvalidSessionFault() {
        super();
    }
    
    public InvalidSessionFault(String message) {
        super(message);
    }
    
    public InvalidSessionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSessionFault(String message, com.netsuite.webservices.platform.faults_2010_2.InvalidSessionFault invalidSessionFault) {
        super(message);
        this.invalidSessionFault = invalidSessionFault;
    }

    public InvalidSessionFault(String message, com.netsuite.webservices.platform.faults_2010_2.InvalidSessionFault invalidSessionFault, Throwable cause) {
        super(message, cause);
        this.invalidSessionFault = invalidSessionFault;
    }

    public com.netsuite.webservices.platform.faults_2010_2.InvalidSessionFault getFaultInfo() {
        return this.invalidSessionFault;
    }
}
