
/*
 * 
 */

package com.netsuite.webservices.platform_2010_2;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Apr 26 17:35:33 ART 2011
 * Generated source version: 2.3.0
 * 
 */


@WebServiceClient(name = "NetSuiteService", 
                  wsdlLocation = "https://webservices.netsuite.com/wsdl/v2010_2_0/netsuite.wsdl",
                  targetNamespace = "urn:platform_2010_2.webservices.netsuite.com") 
public class NetSuiteService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:platform_2010_2.webservices.netsuite.com", "NetSuiteService");
    public final static QName NetSuitePort = new QName("urn:platform_2010_2.webservices.netsuite.com", "NetSuitePort");
    static {
        URL url = null;
        try {
            url = new URL("https://webservices.netsuite.com/wsdl/v2010_2_0/netsuite.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://webservices.netsuite.com/wsdl/v2010_2_0/netsuite.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NetSuiteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NetSuiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetSuiteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns NetSuitePortType
     */
    @WebEndpoint(name = "NetSuitePort")
    public NetSuitePortType getNetSuitePort() {
        return super.getPort(NetSuitePort, NetSuitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetSuitePortType
     */
    @WebEndpoint(name = "NetSuitePort")
    public NetSuitePortType getNetSuitePort(WebServiceFeature... features) {
        return super.getPort(NetSuitePort, NetSuitePortType.class, features);
    }

}
