/**
 * Country.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.mule.module.netsuite.api.internal;

public class Country implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected Country(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String __afghanistan = "_afghanistan";
    public static final java.lang.String __albania = "_albania";
    public static final java.lang.String __algeria = "_algeria";
    public static final java.lang.String __americanSamoa = "_americanSamoa";
    public static final java.lang.String __andorra = "_andorra";
    public static final java.lang.String __angola = "_angola";
    public static final java.lang.String __anguilla = "_anguilla";
    public static final java.lang.String __antarctica = "_antarctica";
    public static final java.lang.String __antiguaAndBarbuda = "_antiguaAndBarbuda";
    public static final java.lang.String __argentina = "_argentina";
    public static final java.lang.String __armenia = "_armenia";
    public static final java.lang.String __aruba = "_aruba";
    public static final java.lang.String __australia = "_australia";
    public static final java.lang.String __austria = "_austria";
    public static final java.lang.String __azerbaijan = "_azerbaijan";
    public static final java.lang.String __bahamas = "_bahamas";
    public static final java.lang.String __bahrain = "_bahrain";
    public static final java.lang.String __bangladesh = "_bangladesh";
    public static final java.lang.String __barbados = "_barbados";
    public static final java.lang.String __belarus = "_belarus";
    public static final java.lang.String __belgium = "_belgium";
    public static final java.lang.String __belize = "_belize";
    public static final java.lang.String __benin = "_benin";
    public static final java.lang.String __bermuda = "_bermuda";
    public static final java.lang.String __bhutan = "_bhutan";
    public static final java.lang.String __bolivia = "_bolivia";
    public static final java.lang.String __bosniaAndHerzegovina = "_bosniaAndHerzegovina";
    public static final java.lang.String __botswana = "_botswana";
    public static final java.lang.String __bouvetIsland = "_bouvetIsland";
    public static final java.lang.String __brazil = "_brazil";
    public static final java.lang.String __britishIndianOceanTerritory = "_britishIndianOceanTerritory";
    public static final java.lang.String __bruneiDarussalam = "_bruneiDarussalam";
    public static final java.lang.String __bulgaria = "_bulgaria";
    public static final java.lang.String __burkinaFaso = "_burkinaFaso";
    public static final java.lang.String __burundi = "_burundi";
    public static final java.lang.String __cambodia = "_cambodia";
    public static final java.lang.String __cameroon = "_cameroon";
    public static final java.lang.String __canada = "_canada";
    public static final java.lang.String __capVerde = "_capVerde";
    public static final java.lang.String __caymanIslands = "_caymanIslands";
    public static final java.lang.String __centralAfricanRepublic = "_centralAfricanRepublic";
    public static final java.lang.String __chad = "_chad";
    public static final java.lang.String __chile = "_chile";
    public static final java.lang.String __china = "_china";
    public static final java.lang.String __christmasIsland = "_christmasIsland";
    public static final java.lang.String __cocosKeelingIslands = "_cocosKeelingIslands";
    public static final java.lang.String __colombia = "_colombia";
    public static final java.lang.String __comoros = "_comoros";
    public static final java.lang.String __congoDemocraticPeoplesRepublic = "_congoDemocraticPeoplesRepublic";
    public static final java.lang.String __congoRepublicOf = "_congoRepublicOf";
    public static final java.lang.String __cookIslands = "_cookIslands";
    public static final java.lang.String __costaRica = "_costaRica";
    public static final java.lang.String __coteDIvoire = "_coteDIvoire";
    public static final java.lang.String __croatiaHrvatska = "_croatiaHrvatska";
    public static final java.lang.String __cuba = "_cuba";
    public static final java.lang.String __cyprus = "_cyprus";
    public static final java.lang.String __czechRepublic = "_czechRepublic";
    public static final java.lang.String __denmark = "_denmark";
    public static final java.lang.String __djibouti = "_djibouti";
    public static final java.lang.String __dominica = "_dominica";
    public static final java.lang.String __dominicanRepublic = "_dominicanRepublic";
    public static final java.lang.String __eastTimor = "_eastTimor";
    public static final java.lang.String __ecuador = "_ecuador";
    public static final java.lang.String __egypt = "_egypt";
    public static final java.lang.String __elSalvador = "_elSalvador";
    public static final java.lang.String __equatorialGuinea = "_equatorialGuinea";
    public static final java.lang.String __eritrea = "_eritrea";
    public static final java.lang.String __estonia = "_estonia";
    public static final java.lang.String __ethiopia = "_ethiopia";
    public static final java.lang.String __falklandIslandsMalvina = "_falklandIslandsMalvina";
    public static final java.lang.String __faroeIslands = "_faroeIslands";
    public static final java.lang.String __fiji = "_fiji";
    public static final java.lang.String __finland = "_finland";
    public static final java.lang.String __france = "_france";
    public static final java.lang.String __frenchGuiana = "_frenchGuiana";
    public static final java.lang.String __frenchPolynesia = "_frenchPolynesia";
    public static final java.lang.String __frenchSouthernTerritories = "_frenchSouthernTerritories";
    public static final java.lang.String __gabon = "_gabon";
    public static final java.lang.String __gambia = "_gambia";
    public static final java.lang.String __georgia = "_georgia";
    public static final java.lang.String __germany = "_germany";
    public static final java.lang.String __ghana = "_ghana";
    public static final java.lang.String __gibraltar = "_gibraltar";
    public static final java.lang.String __greece = "_greece";
    public static final java.lang.String __greenland = "_greenland";
    public static final java.lang.String __grenada = "_grenada";
    public static final java.lang.String __guadeloupe = "_guadeloupe";
    public static final java.lang.String __guam = "_guam";
    public static final java.lang.String __guatemala = "_guatemala";
    public static final java.lang.String __guernsey = "_guernsey";
    public static final java.lang.String __guinea = "_guinea";
    public static final java.lang.String __guineaBissau = "_guineaBissau";
    public static final java.lang.String __guyana = "_guyana";
    public static final java.lang.String __haiti = "_haiti";
    public static final java.lang.String __heardAndMcDonaldIslands = "_heardAndMcDonaldIslands";
    public static final java.lang.String __holySeeCityVaticanState = "_holySeeCityVaticanState";
    public static final java.lang.String __honduras = "_honduras";
    public static final java.lang.String __hongKong = "_hongKong";
    public static final java.lang.String __hungary = "_hungary";
    public static final java.lang.String __iceland = "_iceland";
    public static final java.lang.String __india = "_india";
    public static final java.lang.String __indonesia = "_indonesia";
    public static final java.lang.String __iranIslamicRepublicOf = "_iranIslamicRepublicOf";
    public static final java.lang.String __iraq = "_iraq";
    public static final java.lang.String __ireland = "_ireland";
    public static final java.lang.String __isleOfMan = "_isleOfMan";
    public static final java.lang.String __israel = "_israel";
    public static final java.lang.String __italy = "_italy";
    public static final java.lang.String __jamaica = "_jamaica";
    public static final java.lang.String __japan = "_japan";
    public static final java.lang.String __jersey = "_jersey";
    public static final java.lang.String __jordan = "_jordan";
    public static final java.lang.String __kazakhstan = "_kazakhstan";
    public static final java.lang.String __kenya = "_kenya";
    public static final java.lang.String __kiribati = "_kiribati";
    public static final java.lang.String __koreaDemocraticPeoplesRepublic = "_koreaDemocraticPeoplesRepublic";
    public static final java.lang.String __koreaRepublicOf = "_koreaRepublicOf";
    public static final java.lang.String __kuwait = "_kuwait";
    public static final java.lang.String __kyrgyzstan = "_kyrgyzstan";
    public static final java.lang.String __laoPeoplesDemocraticRepublic = "_laoPeoplesDemocraticRepublic";
    public static final java.lang.String __latvia = "_latvia";
    public static final java.lang.String __lebanon = "_lebanon";
    public static final java.lang.String __lesotho = "_lesotho";
    public static final java.lang.String __liberia = "_liberia";
    public static final java.lang.String __libyanArabJamahiriya = "_libyanArabJamahiriya";
    public static final java.lang.String __liechtenstein = "_liechtenstein";
    public static final java.lang.String __lithuania = "_lithuania";
    public static final java.lang.String __luxembourg = "_luxembourg";
    public static final java.lang.String __macau = "_macau";
    public static final java.lang.String __macedonia = "_macedonia";
    public static final java.lang.String __madagascar = "_madagascar";
    public static final java.lang.String __malawi = "_malawi";
    public static final java.lang.String __malaysia = "_malaysia";
    public static final java.lang.String __maldives = "_maldives";
    public static final java.lang.String __mali = "_mali";
    public static final java.lang.String __malta = "_malta";
    public static final java.lang.String __marshallIslands = "_marshallIslands";
    public static final java.lang.String __martinique = "_martinique";
    public static final java.lang.String __mauritania = "_mauritania";
    public static final java.lang.String __mauritius = "_mauritius";
    public static final java.lang.String __mayotte = "_mayotte";
    public static final java.lang.String __mexico = "_mexico";
    public static final java.lang.String __micronesiaFederalStateOf = "_micronesiaFederalStateOf";
    public static final java.lang.String __moldovaRepublicOf = "_moldovaRepublicOf";
    public static final java.lang.String __monaco = "_monaco";
    public static final java.lang.String __mongolia = "_mongolia";
    public static final java.lang.String __montenegro = "_montenegro";
    public static final java.lang.String __montserrat = "_montserrat";
    public static final java.lang.String __morocco = "_morocco";
    public static final java.lang.String __mozambique = "_mozambique";
    public static final java.lang.String __myanmar = "_myanmar";
    public static final java.lang.String __namibia = "_namibia";
    public static final java.lang.String __nauru = "_nauru";
    public static final java.lang.String __nepal = "_nepal";
    public static final java.lang.String __netherlands = "_netherlands";
    public static final java.lang.String __netherlandsAntilles = "_netherlandsAntilles";
    public static final java.lang.String __newCaledonia = "_newCaledonia";
    public static final java.lang.String __newZealand = "_newZealand";
    public static final java.lang.String __nicaragua = "_nicaragua";
    public static final java.lang.String __niger = "_niger";
    public static final java.lang.String __nigeria = "_nigeria";
    public static final java.lang.String __niue = "_niue";
    public static final java.lang.String __norfolkIsland = "_norfolkIsland";
    public static final java.lang.String __northernMarianaIslands = "_northernMarianaIslands";
    public static final java.lang.String __norway = "_norway";
    public static final java.lang.String __oman = "_oman";
    public static final java.lang.String __pakistan = "_pakistan";
    public static final java.lang.String __palau = "_palau";
    public static final java.lang.String __palestinianTerritories = "_palestinianTerritories";
    public static final java.lang.String __panama = "_panama";
    public static final java.lang.String __papuaNewGuinea = "_papuaNewGuinea";
    public static final java.lang.String __paraguay = "_paraguay";
    public static final java.lang.String __peru = "_peru";
    public static final java.lang.String __philippines = "_philippines";
    public static final java.lang.String __pitcairnIsland = "_pitcairnIsland";
    public static final java.lang.String __poland = "_poland";
    public static final java.lang.String __portugal = "_portugal";
    public static final java.lang.String __puertoRico = "_puertoRico";
    public static final java.lang.String __qatar = "_qatar";
    public static final java.lang.String __reunionIsland = "_reunionIsland";
    public static final java.lang.String __romania = "_romania";
    public static final java.lang.String __russianFederation = "_russianFederation";
    public static final java.lang.String __rwanda = "_rwanda";
    public static final java.lang.String __saintKittsAndNevis = "_saintKittsAndNevis";
    public static final java.lang.String __saintLucia = "_saintLucia";
    public static final java.lang.String __saintVincentAndTheGrenadines = "_saintVincentAndTheGrenadines";
    public static final java.lang.String __sanMarino = "_sanMarino";
    public static final java.lang.String __saoTomeAndPrincipe = "_saoTomeAndPrincipe";
    public static final java.lang.String __saudiArabia = "_saudiArabia";
    public static final java.lang.String __senegal = "_senegal";
    public static final java.lang.String __serbia = "_serbia";
    public static final java.lang.String __seychelles = "_seychelles";
    public static final java.lang.String __sierraLeone = "_sierraLeone";
    public static final java.lang.String __singapore = "_singapore";
    public static final java.lang.String __slovakRepublic = "_slovakRepublic";
    public static final java.lang.String __slovenia = "_slovenia";
    public static final java.lang.String __solomonIslands = "_solomonIslands";
    public static final java.lang.String __somalia = "_somalia";
    public static final java.lang.String __southAfrica = "_southAfrica";
    public static final java.lang.String __southGeorgia = "_southGeorgia";
    public static final java.lang.String __spain = "_spain";
    public static final java.lang.String __sriLanka = "_sriLanka";
    public static final java.lang.String __stHelena = "_stHelena";
    public static final java.lang.String __stPierreAndMiquelon = "_stPierreAndMiquelon";
    public static final java.lang.String __sudan = "_sudan";
    public static final java.lang.String __suriname = "_suriname";
    public static final java.lang.String __svalbardAndJanMayenIslands = "_svalbardAndJanMayenIslands";
    public static final java.lang.String __swaziland = "_swaziland";
    public static final java.lang.String __sweden = "_sweden";
    public static final java.lang.String __switzerland = "_switzerland";
    public static final java.lang.String __syrianArabRepublic = "_syrianArabRepublic";
    public static final java.lang.String __taiwan = "_taiwan";
    public static final java.lang.String __tajikistan = "_tajikistan";
    public static final java.lang.String __tanzania = "_tanzania";
    public static final java.lang.String __thailand = "_thailand";
    public static final java.lang.String __togo = "_togo";
    public static final java.lang.String __tokelau = "_tokelau";
    public static final java.lang.String __tonga = "_tonga";
    public static final java.lang.String __trinidadAndTobago = "_trinidadAndTobago";
    public static final java.lang.String __tunisia = "_tunisia";
    public static final java.lang.String __turkey = "_turkey";
    public static final java.lang.String __turkmenistan = "_turkmenistan";
    public static final java.lang.String __turksAndCaicosIslands = "_turksAndCaicosIslands";
    public static final java.lang.String __tuvalu = "_tuvalu";
    public static final java.lang.String __uganda = "_uganda";
    public static final java.lang.String __ukraine = "_ukraine";
    public static final java.lang.String __unitedArabEmirates = "_unitedArabEmirates";
    public static final java.lang.String __unitedKingdomGB = "_unitedKingdomGB";
    public static final java.lang.String __unitedStates = "_unitedStates";
    public static final java.lang.String __uruguay = "_uruguay";
    public static final java.lang.String __uSMinorOutlyingIslands = "_uSMinorOutlyingIslands";
    public static final java.lang.String __uzbekistan = "_uzbekistan";
    public static final java.lang.String __vanuatu = "_vanuatu";
    public static final java.lang.String __venezuela = "_venezuela";
    public static final java.lang.String __vietnam = "_vietnam";
    public static final java.lang.String __virginIslandsBritish = "_virginIslandsBritish";
    public static final java.lang.String __virginIslandsUSA = "_virginIslandsUSA";
    public static final java.lang.String __wallisAndFutunaIslands = "_wallisAndFutunaIslands";
    public static final java.lang.String __westernSahara = "_westernSahara";
    public static final java.lang.String __westernSamoa = "_westernSamoa";
    public static final java.lang.String __yemen = "_yemen";
    public static final java.lang.String __yugoslavia = "_yugoslavia";
    public static final java.lang.String __zambia = "_zambia";
    public static final java.lang.String __zimbabwe = "_zimbabwe";
    public static final Country _afghanistan = new Country(__afghanistan);
    public static final Country _albania = new Country(__albania);
    public static final Country _algeria = new Country(__algeria);
    public static final Country _americanSamoa = new Country(__americanSamoa);
    public static final Country _andorra = new Country(__andorra);
    public static final Country _angola = new Country(__angola);
    public static final Country _anguilla = new Country(__anguilla);
    public static final Country _antarctica = new Country(__antarctica);
    public static final Country _antiguaAndBarbuda = new Country(__antiguaAndBarbuda);
    public static final Country _argentina = new Country(__argentina);
    public static final Country _armenia = new Country(__armenia);
    public static final Country _aruba = new Country(__aruba);
    public static final Country _australia = new Country(__australia);
    public static final Country _austria = new Country(__austria);
    public static final Country _azerbaijan = new Country(__azerbaijan);
    public static final Country _bahamas = new Country(__bahamas);
    public static final Country _bahrain = new Country(__bahrain);
    public static final Country _bangladesh = new Country(__bangladesh);
    public static final Country _barbados = new Country(__barbados);
    public static final Country _belarus = new Country(__belarus);
    public static final Country _belgium = new Country(__belgium);
    public static final Country _belize = new Country(__belize);
    public static final Country _benin = new Country(__benin);
    public static final Country _bermuda = new Country(__bermuda);
    public static final Country _bhutan = new Country(__bhutan);
    public static final Country _bolivia = new Country(__bolivia);
    public static final Country _bosniaAndHerzegovina = new Country(__bosniaAndHerzegovina);
    public static final Country _botswana = new Country(__botswana);
    public static final Country _bouvetIsland = new Country(__bouvetIsland);
    public static final Country _brazil = new Country(__brazil);
    public static final Country _britishIndianOceanTerritory = new Country(__britishIndianOceanTerritory);
    public static final Country _bruneiDarussalam = new Country(__bruneiDarussalam);
    public static final Country _bulgaria = new Country(__bulgaria);
    public static final Country _burkinaFaso = new Country(__burkinaFaso);
    public static final Country _burundi = new Country(__burundi);
    public static final Country _cambodia = new Country(__cambodia);
    public static final Country _cameroon = new Country(__cameroon);
    public static final Country _canada = new Country(__canada);
    public static final Country _capVerde = new Country(__capVerde);
    public static final Country _caymanIslands = new Country(__caymanIslands);
    public static final Country _centralAfricanRepublic = new Country(__centralAfricanRepublic);
    public static final Country _chad = new Country(__chad);
    public static final Country _chile = new Country(__chile);
    public static final Country _china = new Country(__china);
    public static final Country _christmasIsland = new Country(__christmasIsland);
    public static final Country _cocosKeelingIslands = new Country(__cocosKeelingIslands);
    public static final Country _colombia = new Country(__colombia);
    public static final Country _comoros = new Country(__comoros);
    public static final Country _congoDemocraticPeoplesRepublic = new Country(__congoDemocraticPeoplesRepublic);
    public static final Country _congoRepublicOf = new Country(__congoRepublicOf);
    public static final Country _cookIslands = new Country(__cookIslands);
    public static final Country _costaRica = new Country(__costaRica);
    public static final Country _coteDIvoire = new Country(__coteDIvoire);
    public static final Country _croatiaHrvatska = new Country(__croatiaHrvatska);
    public static final Country _cuba = new Country(__cuba);
    public static final Country _cyprus = new Country(__cyprus);
    public static final Country _czechRepublic = new Country(__czechRepublic);
    public static final Country _denmark = new Country(__denmark);
    public static final Country _djibouti = new Country(__djibouti);
    public static final Country _dominica = new Country(__dominica);
    public static final Country _dominicanRepublic = new Country(__dominicanRepublic);
    public static final Country _eastTimor = new Country(__eastTimor);
    public static final Country _ecuador = new Country(__ecuador);
    public static final Country _egypt = new Country(__egypt);
    public static final Country _elSalvador = new Country(__elSalvador);
    public static final Country _equatorialGuinea = new Country(__equatorialGuinea);
    public static final Country _eritrea = new Country(__eritrea);
    public static final Country _estonia = new Country(__estonia);
    public static final Country _ethiopia = new Country(__ethiopia);
    public static final Country _falklandIslandsMalvina = new Country(__falklandIslandsMalvina);
    public static final Country _faroeIslands = new Country(__faroeIslands);
    public static final Country _fiji = new Country(__fiji);
    public static final Country _finland = new Country(__finland);
    public static final Country _france = new Country(__france);
    public static final Country _frenchGuiana = new Country(__frenchGuiana);
    public static final Country _frenchPolynesia = new Country(__frenchPolynesia);
    public static final Country _frenchSouthernTerritories = new Country(__frenchSouthernTerritories);
    public static final Country _gabon = new Country(__gabon);
    public static final Country _gambia = new Country(__gambia);
    public static final Country _georgia = new Country(__georgia);
    public static final Country _germany = new Country(__germany);
    public static final Country _ghana = new Country(__ghana);
    public static final Country _gibraltar = new Country(__gibraltar);
    public static final Country _greece = new Country(__greece);
    public static final Country _greenland = new Country(__greenland);
    public static final Country _grenada = new Country(__grenada);
    public static final Country _guadeloupe = new Country(__guadeloupe);
    public static final Country _guam = new Country(__guam);
    public static final Country _guatemala = new Country(__guatemala);
    public static final Country _guernsey = new Country(__guernsey);
    public static final Country _guinea = new Country(__guinea);
    public static final Country _guineaBissau = new Country(__guineaBissau);
    public static final Country _guyana = new Country(__guyana);
    public static final Country _haiti = new Country(__haiti);
    public static final Country _heardAndMcDonaldIslands = new Country(__heardAndMcDonaldIslands);
    public static final Country _holySeeCityVaticanState = new Country(__holySeeCityVaticanState);
    public static final Country _honduras = new Country(__honduras);
    public static final Country _hongKong = new Country(__hongKong);
    public static final Country _hungary = new Country(__hungary);
    public static final Country _iceland = new Country(__iceland);
    public static final Country _india = new Country(__india);
    public static final Country _indonesia = new Country(__indonesia);
    public static final Country _iranIslamicRepublicOf = new Country(__iranIslamicRepublicOf);
    public static final Country _iraq = new Country(__iraq);
    public static final Country _ireland = new Country(__ireland);
    public static final Country _isleOfMan = new Country(__isleOfMan);
    public static final Country _israel = new Country(__israel);
    public static final Country _italy = new Country(__italy);
    public static final Country _jamaica = new Country(__jamaica);
    public static final Country _japan = new Country(__japan);
    public static final Country _jersey = new Country(__jersey);
    public static final Country _jordan = new Country(__jordan);
    public static final Country _kazakhstan = new Country(__kazakhstan);
    public static final Country _kenya = new Country(__kenya);
    public static final Country _kiribati = new Country(__kiribati);
    public static final Country _koreaDemocraticPeoplesRepublic = new Country(__koreaDemocraticPeoplesRepublic);
    public static final Country _koreaRepublicOf = new Country(__koreaRepublicOf);
    public static final Country _kuwait = new Country(__kuwait);
    public static final Country _kyrgyzstan = new Country(__kyrgyzstan);
    public static final Country _laoPeoplesDemocraticRepublic = new Country(__laoPeoplesDemocraticRepublic);
    public static final Country _latvia = new Country(__latvia);
    public static final Country _lebanon = new Country(__lebanon);
    public static final Country _lesotho = new Country(__lesotho);
    public static final Country _liberia = new Country(__liberia);
    public static final Country _libyanArabJamahiriya = new Country(__libyanArabJamahiriya);
    public static final Country _liechtenstein = new Country(__liechtenstein);
    public static final Country _lithuania = new Country(__lithuania);
    public static final Country _luxembourg = new Country(__luxembourg);
    public static final Country _macau = new Country(__macau);
    public static final Country _macedonia = new Country(__macedonia);
    public static final Country _madagascar = new Country(__madagascar);
    public static final Country _malawi = new Country(__malawi);
    public static final Country _malaysia = new Country(__malaysia);
    public static final Country _maldives = new Country(__maldives);
    public static final Country _mali = new Country(__mali);
    public static final Country _malta = new Country(__malta);
    public static final Country _marshallIslands = new Country(__marshallIslands);
    public static final Country _martinique = new Country(__martinique);
    public static final Country _mauritania = new Country(__mauritania);
    public static final Country _mauritius = new Country(__mauritius);
    public static final Country _mayotte = new Country(__mayotte);
    public static final Country _mexico = new Country(__mexico);
    public static final Country _micronesiaFederalStateOf = new Country(__micronesiaFederalStateOf);
    public static final Country _moldovaRepublicOf = new Country(__moldovaRepublicOf);
    public static final Country _monaco = new Country(__monaco);
    public static final Country _mongolia = new Country(__mongolia);
    public static final Country _montenegro = new Country(__montenegro);
    public static final Country _montserrat = new Country(__montserrat);
    public static final Country _morocco = new Country(__morocco);
    public static final Country _mozambique = new Country(__mozambique);
    public static final Country _myanmar = new Country(__myanmar);
    public static final Country _namibia = new Country(__namibia);
    public static final Country _nauru = new Country(__nauru);
    public static final Country _nepal = new Country(__nepal);
    public static final Country _netherlands = new Country(__netherlands);
    public static final Country _netherlandsAntilles = new Country(__netherlandsAntilles);
    public static final Country _newCaledonia = new Country(__newCaledonia);
    public static final Country _newZealand = new Country(__newZealand);
    public static final Country _nicaragua = new Country(__nicaragua);
    public static final Country _niger = new Country(__niger);
    public static final Country _nigeria = new Country(__nigeria);
    public static final Country _niue = new Country(__niue);
    public static final Country _norfolkIsland = new Country(__norfolkIsland);
    public static final Country _northernMarianaIslands = new Country(__northernMarianaIslands);
    public static final Country _norway = new Country(__norway);
    public static final Country _oman = new Country(__oman);
    public static final Country _pakistan = new Country(__pakistan);
    public static final Country _palau = new Country(__palau);
    public static final Country _palestinianTerritories = new Country(__palestinianTerritories);
    public static final Country _panama = new Country(__panama);
    public static final Country _papuaNewGuinea = new Country(__papuaNewGuinea);
    public static final Country _paraguay = new Country(__paraguay);
    public static final Country _peru = new Country(__peru);
    public static final Country _philippines = new Country(__philippines);
    public static final Country _pitcairnIsland = new Country(__pitcairnIsland);
    public static final Country _poland = new Country(__poland);
    public static final Country _portugal = new Country(__portugal);
    public static final Country _puertoRico = new Country(__puertoRico);
    public static final Country _qatar = new Country(__qatar);
    public static final Country _reunionIsland = new Country(__reunionIsland);
    public static final Country _romania = new Country(__romania);
    public static final Country _russianFederation = new Country(__russianFederation);
    public static final Country _rwanda = new Country(__rwanda);
    public static final Country _saintKittsAndNevis = new Country(__saintKittsAndNevis);
    public static final Country _saintLucia = new Country(__saintLucia);
    public static final Country _saintVincentAndTheGrenadines = new Country(__saintVincentAndTheGrenadines);
    public static final Country _sanMarino = new Country(__sanMarino);
    public static final Country _saoTomeAndPrincipe = new Country(__saoTomeAndPrincipe);
    public static final Country _saudiArabia = new Country(__saudiArabia);
    public static final Country _senegal = new Country(__senegal);
    public static final Country _serbia = new Country(__serbia);
    public static final Country _seychelles = new Country(__seychelles);
    public static final Country _sierraLeone = new Country(__sierraLeone);
    public static final Country _singapore = new Country(__singapore);
    public static final Country _slovakRepublic = new Country(__slovakRepublic);
    public static final Country _slovenia = new Country(__slovenia);
    public static final Country _solomonIslands = new Country(__solomonIslands);
    public static final Country _somalia = new Country(__somalia);
    public static final Country _southAfrica = new Country(__southAfrica);
    public static final Country _southGeorgia = new Country(__southGeorgia);
    public static final Country _spain = new Country(__spain);
    public static final Country _sriLanka = new Country(__sriLanka);
    public static final Country _stHelena = new Country(__stHelena);
    public static final Country _stPierreAndMiquelon = new Country(__stPierreAndMiquelon);
    public static final Country _sudan = new Country(__sudan);
    public static final Country _suriname = new Country(__suriname);
    public static final Country _svalbardAndJanMayenIslands = new Country(__svalbardAndJanMayenIslands);
    public static final Country _swaziland = new Country(__swaziland);
    public static final Country _sweden = new Country(__sweden);
    public static final Country _switzerland = new Country(__switzerland);
    public static final Country _syrianArabRepublic = new Country(__syrianArabRepublic);
    public static final Country _taiwan = new Country(__taiwan);
    public static final Country _tajikistan = new Country(__tajikistan);
    public static final Country _tanzania = new Country(__tanzania);
    public static final Country _thailand = new Country(__thailand);
    public static final Country _togo = new Country(__togo);
    public static final Country _tokelau = new Country(__tokelau);
    public static final Country _tonga = new Country(__tonga);
    public static final Country _trinidadAndTobago = new Country(__trinidadAndTobago);
    public static final Country _tunisia = new Country(__tunisia);
    public static final Country _turkey = new Country(__turkey);
    public static final Country _turkmenistan = new Country(__turkmenistan);
    public static final Country _turksAndCaicosIslands = new Country(__turksAndCaicosIslands);
    public static final Country _tuvalu = new Country(__tuvalu);
    public static final Country _uganda = new Country(__uganda);
    public static final Country _ukraine = new Country(__ukraine);
    public static final Country _unitedArabEmirates = new Country(__unitedArabEmirates);
    public static final Country _unitedKingdomGB = new Country(__unitedKingdomGB);
    public static final Country _unitedStates = new Country(__unitedStates);
    public static final Country _uruguay = new Country(__uruguay);
    public static final Country _uSMinorOutlyingIslands = new Country(__uSMinorOutlyingIslands);
    public static final Country _uzbekistan = new Country(__uzbekistan);
    public static final Country _vanuatu = new Country(__vanuatu);
    public static final Country _venezuela = new Country(__venezuela);
    public static final Country _vietnam = new Country(__vietnam);
    public static final Country _virginIslandsBritish = new Country(__virginIslandsBritish);
    public static final Country _virginIslandsUSA = new Country(__virginIslandsUSA);
    public static final Country _wallisAndFutunaIslands = new Country(__wallisAndFutunaIslands);
    public static final Country _westernSahara = new Country(__westernSahara);
    public static final Country _westernSamoa = new Country(__westernSamoa);
    public static final Country _yemen = new Country(__yemen);
    public static final Country _yugoslavia = new Country(__yugoslavia);
    public static final Country _zambia = new Country(__zambia);
    public static final Country _zimbabwe = new Country(__zimbabwe);
    public java.lang.String getValue() { return _value_;}
    public static Country fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        Country enumeration = (Country)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static Country fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Country.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("urn:types.common_2010_2.platform.webservices.netsuite.com", "Country"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
