/**
 * NetSuitePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.mule.module.netsuite.api.internal;

public interface NetSuitePortType extends java.rmi.Remote {
    public org.mule.module.netsuite.api.internal.SessionResponse login(org.mule.module.netsuite.api.internal.Passport passport) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.InvalidVersionFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.InsufficientPermissionFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidAccountFault;
    public org.mule.module.netsuite.api.internal.SessionResponse ssoLogin(org.mule.module.netsuite.api.internal.SsoPassport ssoPassport) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.InvalidVersionFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.InsufficientPermissionFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidAccountFault;
    public org.mule.module.netsuite.api.internal.SessionResponse mapSso(org.mule.module.netsuite.api.internal.SsoCredentials ssoCredentials) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.InvalidVersionFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.InsufficientPermissionFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidAccountFault;
    public org.mule.module.netsuite.api.internal.SessionResponse changePasswordOrEmail(org.mule.module.netsuite.api.internal.ChangePasswordOrEmailCredentials changePasswordOrEmailCredentials) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.InvalidVersionFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.InsufficientPermissionFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidAccountFault;
    public org.mule.module.netsuite.api.internal.SessionResponse logout() throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponse add(org.mule.module.netsuite.api.internal.Record record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponse delete(org.mule.module.netsuite.api.internal.BaseRef baseRef) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.SearchResult search(org.mule.module.netsuite.api.internal.SearchRecord searchRecord) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.SearchResult searchMore(int pageIndex) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.SearchResult searchMoreWithId(java.lang.String searchId, int pageIndex) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.SearchResult searchNext() throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponse update(org.mule.module.netsuite.api.internal.Record record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponseList addList(org.mule.module.netsuite.api.internal.Record[] record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponseList deleteList(org.mule.module.netsuite.api.internal.BaseRef[] baseRef) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponseList updateList(org.mule.module.netsuite.api.internal.Record[] record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.ReadResponse get(org.mule.module.netsuite.api.internal.BaseRef baseRef) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.ReadResponseList getList(org.mule.module.netsuite.api.internal.BaseRef[] baseRef) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetAllResult getAll(org.mule.module.netsuite.api.internal.GetAllRecord record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetSavedSearchResult getSavedSearch(org.mule.module.netsuite.api.internal.GetSavedSearchRecord record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetCustomizationIdResult getCustomizationId(org.mule.module.netsuite.api.internal.CustomizationType customizationType, boolean includeInactives) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.ReadResponse initialize(org.mule.module.netsuite.api.internal.InitializeRecord initializeRecord) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.ReadResponseList initializeList(org.mule.module.netsuite.api.internal.InitializeRecord[] initializeRecord) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetSelectValueResult getSelectValue(org.mule.module.netsuite.api.internal.GetSelectValueFieldDescription fieldDescription, int pageIndex) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetItemAvailabilityResult getItemAvailability(org.mule.module.netsuite.api.internal.ItemAvailabilityFilter itemAvailabilityFilter) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetBudgetExchangeRateResult getBudgetExchangeRate(org.mule.module.netsuite.api.internal.BudgetExchangeRateFilter budgetExchangeRateFilter) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetConsolidatedExchangeRateResult getConsolidatedExchangeRate(org.mule.module.netsuite.api.internal.ConsolidatedExchangeRateFilter consolidatedExchangeRateFilter) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetPostingTransactionSummaryResult getPostingTransactionSummary(org.mule.module.netsuite.api.internal.PostingTransactionSummaryField fields, org.mule.module.netsuite.api.internal.PostingTransactionSummaryFilter filters, int pageIndex) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.GetServerTimeResult getServerTime() throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponse attach(org.mule.module.netsuite.api.internal.AttachReference attachReference) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponse detach(org.mule.module.netsuite.api.internal.DetachReference detachReference) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponse updateInviteeStatus(org.mule.module.netsuite.api.internal.UpdateInviteeStatusReference updateInviteeStatusReference) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.WriteResponseList updateInviteeStatusList(org.mule.module.netsuite.api.internal.UpdateInviteeStatusReference[] updateInviteeStatusReference) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult asyncAddList(org.mule.module.netsuite.api.internal.Record[] record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult asyncUpdateList(org.mule.module.netsuite.api.internal.Record[] record) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult asyncDeleteList(org.mule.module.netsuite.api.internal.BaseRef[] baseRef) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult asyncGetList(org.mule.module.netsuite.api.internal.BaseRef[] baseRef) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult asyncInitializeList(org.mule.module.netsuite.api.internal.InitializeRecord[] initializeRecord) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult asyncSearch(org.mule.module.netsuite.api.internal.SearchRecord searchRecord) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
    public org.mule.module.netsuite.api.internal.AsyncResult getAsyncResult(java.lang.String jobId, int pageIndex) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault, org.mule.module.netsuite.api.internal.AsyncFault;
    public org.mule.module.netsuite.api.internal.AsyncStatusResult checkAsyncStatus(java.lang.String jobId) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault, org.mule.module.netsuite.api.internal.AsyncFault;
    public org.mule.module.netsuite.api.internal.GetDeletedResult getDeleted(org.mule.module.netsuite.api.internal.GetDeletedFilter getDeletedFilter) throws java.rmi.RemoteException, org.mule.module.netsuite.api.internal.ExceededRequestSizeFault, org.mule.module.netsuite.api.internal.InvalidCredentialsFault, org.mule.module.netsuite.api.internal.ExceededUsageLimitFault, org.mule.module.netsuite.api.internal.ExceededRequestLimitFault, org.mule.module.netsuite.api.internal.ExceededRecordCountFault, org.mule.module.netsuite.api.internal.UnexpectedErrorFault, org.mule.module.netsuite.api.internal.InvalidSessionFault;
}
